name: Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [
            # From https://github.com/nodejs/Release
            '22.x', # EoL by 2027-04-30
            '24.x', # EoL by 2028-04-30
            '26.x', # EoL by 2029-04-30
            'latest',
          ]

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test TypeScript
        run: pnpm run test:typescript

      - name: Unit tests
        run: pnpm run test

      - name: Completeness check
        run: pnpm run test:completeness

      - name: Check docs source lines are up to date
        run: |
          pnpm run docs:update-sources
          git diff --exit-code docs/content/docs/api/

      - name: Lints
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Test type inference
        run: pnpm run test:types

      - name: Tree-shaking
        run: pnpm run test:treeshake

      - name: Lint packages
        run: pnpm run lint:package
